---
title: "module_10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(roxygen2)
library(DT)

```


# Example without using functions
```{r}

airtemps <- c(212, 30.3, 78, 32)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9
```

# Create a function
```{r}
#' Convert temperature data from Fahrenheit to Celsius
#'
#' @param fahr Temperature data in degrees Fahrenheit to be converted
#' @return temperature value in degrees Celsius
#' @keywords conversion
#' @export
#' @examples
#' fahr_to_celsius(32)
#' fahr_to_celsius(c(32, 212, 72))

# Your code goes here
fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32)*5/9
  return(celsius)
}

```


# Test our function
```{r}
celsius4 <- fahr_to_celsius(airtemps[1])
celsius4
celsius1 == celsius4
celsius <- fahr_to_celsius(airtemps)

```

# New function
```{r}
#' Convert temperature data from Celsius to Fahrenheit
#'
#' @param celsius Temperature data in degrees Celsius to be converted
#' @return temperature value in degrees Fahrenheit
#' @keywords conversion
#' @export
#' @examples
#' celsius_to_fahr(0)
#' celsius_to_fahr(c(0, 100, 30.3))

# Your code goes here
celsius_to_fahr <- function(celsius) {
    fahr <- celsius*9/5 + 32
    return(fahr)
}

result <- celsius_to_fahr(celsius)
airtemps == result
```

# New function
```{r}
convert_temps <- function(fahr) {
  celsius <- (fahr-32)*5/9
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius=celsius, kelvin=kelvin))
}

temps_df <- data.frame(convert_temps(seq(-100,100,10)))
datatable(temps_df)
```

```{r}
library(ggplot2)
custom_theme <- function(base_size = 9) {
    ggplot2::theme(
      # axis.ticks       = ggplot2::element_blank(),
      text             = ggplot2::element_text(family = 'Arial', color = 'gray30', size = base_size),
      plot.title       = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'),
      panel.background = ggplot2::element_blank(),
      legend.position  = 'right',
      # panel.border     = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      # panel.grid.major = ggplot2::element_line(colour = 'grey90', size = .25),
      legend.key       = ggplot2::element_rect(colour = NA, fill = NA),
      axis.line        = ggplot2::element_line()
      )
}

ggplot(temps_df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point() +
    custom_theme(10)
```

```{r}
scatterplot <- function(df, point_size = 2, font_size=9) {
  ggplot(df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point(size=point_size) +
    custom_theme(font_size)
}

scatterplot(temps_df, point_size=2, font_size = 10) +
  scale_color_gradient(low = "blue", high = "red")
```


